name: iml.env
channels:
  - defaults
dependencies:
  - nb_conda_kernels
  - pandas
  - scipy
  - plotly
  - psutil
  - nb_conda
  - requests
  - numpy
  - scikit-learn
  - python=3.7
  - statsmodels
  - pip
  - pip:
    - gif==3.0.0
    - kaleido==0.2.1
    - pillow==8.1.2
